### PR TITLE
chore: upgrade to erlang 25 and elixir 1.14

### PR DESCRIPTION
**Pull request by nlwstein**
#### Summary of changes
**Asana Ticket:** [💳 Apps run on latest Erlang + Elixir version](https://app.asana.com/0/584764604969369/1203566390445122/f)

Bumps the Erlang / Elixir version to 25 / 1.14 with passing tests. 

#### Reviewer Checklist
- [ ] Any new or changed functions have typespecs
- [ ] Tests were added for any new functionality (don't just rely on Lcov)
- [ ] Meets ticket's acceptance criteria

### CODE REVIEW

**Comment by nlwstein** [comment]
My only concern here is https://github.com/mbta/trike/blob/83a215e0e2d079501c23fa07daf3028385e0cff2/Dockerfile#L33 - do we have a means to test Windows containers?

**Comment by nlwstein** [comment]
> My only concern here is if we have a means to test Windows containers to validate the image build?

I have a method to test this now, will verify tomorrow!

**Comment by paulswartz** [comment]
> My only concern here is if we have a means to test Windows containers to validate the image build?

@nlwstein you can deploy from the branch to `trike-dev` and check the Splunk index to make sure it started properly.

**Review by dks-mbta — APPROVED** [review]

**Comment by paulswartz** [comment]
Given the issues with other applications, you should also test writing messages to `trike-dev` to ensure we can still send them to AWS: you can use `mix kinesis_source` to copy the messages from the production stream.

**Comment by nlwstein** [comment]
> Given the issues with other applications, you should also test writing messages to `trike-dev` to ensure we can still send them to AWS: you can use `mix kinesis_source` to copy the messages from the production stream.

I ran `mix kinesis_source ctd-ocs-raw-messages --host HSCTDTST` and it seemed to work fine - no errors in Splunk and I see lots of logs like this: 

`container_id=ccc83c0c391d 2023-03-09T14:34:30.886 pid=<0.1167.0> socket=#Port<0.9> request_id=146 [info] ocs_event raw="1534054,RGPS,14:34:30,G,U17-235-501,3913,42.3366333333333,71.2551166666667,0.00,46.29" time=~U[2023-03-09 19:34:30.864000Z]`

**Pull request merged**
